#!/usr/bin/env php
<?php declare(strict_types=1);

/*
 * This file is part of PHPSLS.
 *
 * (c) Milan Lesichkov <lesichkovm@gmail.com>
 */

if (version_compare('7.0.0', PHP_VERSION, '>')) {
    fwrite(STDERR,"This version of PHP Serverless is supported on PHP 7.0, 7.1, 7.2, 7.3, PHP 7.4, and PHP 8.0." . PHP_EOL);
    fwrite(STDERR,sprintf("You are using PHP %s (%s)." . PHP_EOL, PHP_VERSION, PHP_BINARY));
    die(1);
}

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('PHPSERVERLESS_COMPOSER_INSTALL', $file);
        break;
    }
}

unset($file);

if (!defined('PHPSERVERLESS_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );
    die(1);
}

$options = getopt('', array('prepend:'));
if (isset($options['prepend'])) {
    require $options['prepend'];
}

unset($options);

$classLoader = require PHPSERVERLESS_COMPOSER_INSTALL;
//PHPServerless\Command::main();

// Customization variables
$appName = "PHPSLS";
$appVersion = '1.0.0';
//$commandClasses = [ \PHPServerless\PhpSls::class ];
$selfUpdateRepository = 'lesichkovm/phpsls';
$configurationFilename = 'phpsls.yml';

// Define our Runner, and pass it the command classes we provide.
//$runner = new \Robo\Runner($commandClasses);
//$runner
//  ->setSelfUpdateRepository($selfUpdateRepository)
//  ->setConfigurationFilename($configurationFilename)
//  ->setClassLoader($classLoader);

// Execute the command and return the result.
//$output = new \Symfony\Component\Console\Output\ConsoleOutput();
//$statusCode = $runner->execute($argv, $appName, $appVersion, $output);

$arguments = \PHPServerless\parseArgs();
$phpSls = new \PHPServerless\PhpSls();
$statusCode = $phpSls->run($arguments['arguments'], $arguments['parameters']);

exit($statusCode);
